name: build

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11.0.5
      uses: actions/setup-java@v3
      with:
        # https://github.com/actions/setup-java#supported-distributions
        distribution: 'microsoft'
        java-version: 11.0.5

    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true --no-transfer-progress package --file pom.xml
